"""second migration

Revision ID: 6aca46295aea
Revises: 1d4b96a490c9
Create Date: 2023-12-22 15:50:42.699073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aca46295aea'
down_revision: Union[str, None] = '1d4b96a490c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_price_data', 'eth_daily_price_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_price_data', sa.Column('eth_daily_price_open', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
