"""added ETH price data tables

Revision ID: fd9195c9dcaa
Revises: 6aca46295aea
Create Date: 2023-12-23 10:45:27.525279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9195c9dcaa'
down_revision: Union[str, None] = '6aca46295aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_eth_price_data',
    sa.Column('daily_datetime_id', sa.DateTime(), nullable=False),
    sa.Column('eth_daily_price_open', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_daily_price_close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_daily_price_high', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_daily_price_low', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_daily_price_vol', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_daily_price_vol_weight_avg', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('daily_datetime_id')
    )
    op.create_table('hour_eth_price_data',
    sa.Column('hour_datetime_id', sa.DateTime(), nullable=False),
    sa.Column('eth_hour_price_open', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_hour_price_close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_hour_price_high', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_hour_price_low', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_hour_price_vol', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_hour_price_vol_weight_avg', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('hour_datetime_id')
    )
    op.create_table('minute_eth_price_data',
    sa.Column('minute_datetime_id', sa.DateTime(), nullable=False),
    sa.Column('eth_minute_price_open', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_minute_price_close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_minute_price_high', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_minute_price_low', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_minute_price_vol', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('eth_minute_price_vol_weight_avg', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('minute_datetime_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minute_eth_price_data')
    op.drop_table('hour_eth_price_data')
    op.drop_table('daily_eth_price_data')
    # ### end Alembic commands ###
